import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Container, Grid, Stack } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';
import styles from '../../styles/Home.module.css'
import { Box } from '@mui/material';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />

      <main style={{paddingTop : 40}}>

      <Container maxWidth="lg">
        <Stack direction="row">

        <Card sx={{ maxWidth: 190, maxHeight :250, borderRadius : 2, margin : 1}}>
          <CardActionArea>
            <CardMedia
              component="img"
              maxHeight="160"
              image="https://play-lh.googleusercontent.com/IhUVzRkz5MokalaeiLulcloc8rxROw0fSPRC7-Lc5zCF_wIfhbxo3qsOjKxYp524B1dY"
              alt="AOV"
            />
            <CardContent>
              <Grid container spacing={0} justifyContent="center">
              <Typography gutterBottom variant="h6" component="article">
                Mobile Legends
              </Typography>
              </Grid>
            </CardContent>
          </CardActionArea>
        </Card>

        <Card sx={{ maxWidth: 190, maxHeight :250, borderRadius : 2, margin : 1}}>
          <CardActionArea>
            <CardMedia
              component="img"
              maxHeight="160"
              image="https://play-lh.googleusercontent.com/YDas3XR6j4LeWbCr4k9vz-SErhSdY_bLXZY_m5uzZjgGMELXYbZHUkBjkbP6gzhdvRk"
              alt="AOV"
            />
            <CardContent>
              <Grid container spacing={0} justifyContent="center">
              <Typography gutterBottom variant="h6" component="article">
                Free Fire
              </Typography>
              </Grid>
            </CardContent>
          </CardActionArea>
        </Card>

        <Card sx={{ maxWidth: 190, maxHeight :250, borderRadius : 2, margin : 1}}>
          <CardActionArea>
            <CardMedia
              component="img"
              maxHeight="160"
              image="https://play-lh.googleusercontent.com/YDas3XR6j4LeWbCr4k9vz-SErhSdY_bLXZY_m5uzZjgGMELXYbZHUkBjkbP6gzhdvRk"
              alt="AOV"
            />
            <CardContent>
              <Grid container spacing={0} justifyContent="center">
              <Typography gutterBottom variant="h6" component="article">
                Free Fire
              </Typography>
              </Grid>
            </CardContent>
          </CardActionArea>
        </Card>
    

        </Stack>
      </Container>


      </main>
    </div>
  )
}

export default Home
