import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Container, Grid, Stack } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';
import styles from '../../styles/Home.module.css'
import { Box } from '@mui/material';
import Card from '@mui/material/Card';
import Avatar from '@mui/material/Avatar';

import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';
import { minWidth } from '@mui/system';
import { dataGame } from '../../data/game';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>

      <CssBaseline />

      <Container maxWidth="xl">

        <Stack direction={{xl : "row"}} justifyContent={"center"} alignItems={"center"} spacing={4} marginBottom={20} marginTop={20}>
          <img
            style={{borderRadius : 360, width : 200, height : 200}}
            src={"/images/flixzstore.jpeg"}
          />
          <Stack>
          <Typography gutterBottom variant="h2" component="p">
            Welcome TO
          </Typography>
          <Typography gutterBottom variant="h2" component="p">
            Flixz Store
          </Typography>
          </Stack>
        </Stack>
   
        <Grid container spacing={{ xs: 2, sm : 4,md: 2,lg : 2,  xl : 2 }} columns={{ xs: 8, sm: 12, md: 16,lg : 20,xl :24 }}>
          {dataGame.map((item, index) => (
            <Grid item xs={4} sm={4} md={4} key={index}>
              <Card sx={{  maxWidth : 260, maxHeight : 330,borderRadius : 5}}>
                  <CardActionArea>
                    <CardMedia
                      sx={{borderRadius : 5}}
                      component="img"
                      image={item.logo}
                      alt="AOV"
                    />
                    <CardContent sx={{height : 80 }}>
                      <Grid container justifyContent={"center"}>
                      <Typography gutterBottom variant="body1" component="p" align='center'>
                        {item.name}
                      </Typography>
                      </Grid>
                    </CardContent>
                  </CardActionArea>
                </Card>
        </Grid>
  ))}
</Grid>


       




      </Container>


      </main>
    </div>
  )
}

export default Home
