import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Container, Grid, Stack } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';
import styles from '../../styles/Home.module.css'
import { Box } from '@mui/material';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';
import { minWidth } from '@mui/system';
import { dataGame } from '../../data/game';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />

      <main style={{paddingTop : 40}}>

      <Container maxWidth="lg">
        <Grid container spacing={{ xs: 2, sm : 4,md: 6,lg : 6,  xl : 6 }} columns={{ xs: 8, sm: 12, md: 16,lg : 20,xl :24 }}>
          {dataGame.map((item, index) => (
            <Grid item xs={4} sm={4} md={4} key={index}>
              
              <Card sx={{  maxWidth : 190, maxHeight : 240,borderRadius : 2}}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      image="https://play-lh.googleusercontent.com/IhUVzRkz5MokalaeiLulcloc8rxROw0fSPRC7-Lc5zCF_wIfhbxo3qsOjKxYp524B1dY"
                      alt="AOV"
                    />
                    <CardContent sx={{height : 80}}>
                      <Grid container spacing={0} justifyContent="center">
                      <Typography gutterBottom variant="body1" component="p">
                        {item.name}
                      </Typography>
                      </Grid>
                    </CardContent>
                  </CardActionArea>
                </Card>
        </Grid>
  ))}
</Grid>


       




      </Container>


      </main>
    </div>
  )
}

export default Home
